### ISSUE TITLE
你好，可以麻烦看一下是什么问题吗

### ISSUE THREAD

**Issue by Zyy-boop** [geikun/YS-ios-GC#1]
![334822ae335638ea359fd2e3accdd67e](https://user-images.githubusercontent.com/74231782/226677408-1feb6ef5-8b95-4e24-8026-f433ebdf5480.jpeg)
![0a5dac2e7faa73126fc8443763b22814](https://user-images.githubusercontent.com/74231782/226678313-3e24799c-6a54-470a-817b-d2721c7b0023.jpeg)
![image](https://user-images.githubusercontent.com/74231782/226678371-6840f850-d9be-48f0-be1f-090f8a99097b.png)

模块是下载资源的时候可以进入，但是一旦改了模块的地址就4201，服务端用的mitm做转发。用的是仓库的核心。

**Comment by xlpmyxhdr** [comment]
请认真，仔细看wiki

**Comment by Zyy-boop** [comment]
> 请认真，仔细看wiki
٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ
